### ISSUE TITLE
Sort repos by number of commits

### ISSUE THREAD

**Issue by poorgeek** [LinuxBozo/18f-bpa-repos#2]
It might be helpful to see repos by the total number of commits.

**Comment by LinuxBozo** [comment]
Might be nice, but the github API doesn't provide that information that I can see.

Here's an example search result:
https://api.github.com/search/repositories?q=18fagilebpa

And an individual repo result:
https://api.github.com/repos/devis/18FAgileBPA

**Comment by poorgeek** [comment]
https://api.github.com/repos/devis/18FAgileBPA/commits will list all of the commits made per https://developer.github.com/v3/repos/commits/#list-commits-on-a-repository

**Comment by LinuxBozo** [comment]
That's quite a few API calls, and quite a bit of data, just to get a total count of commits for each repo so you can sort by that.

**Comment by poorgeek** [comment]
Yeah, once I saw what it would take I realised it might not be practical with the current setup.

**Comment by LinuxBozo** [comment]
With that, closing for now..
